/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organizedchaos;
  

/**
 *
 * @author CATATO
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    String producto; //Toma lo que ingrese el usuario en la caja desplegable de productos.
    String cantidad; //Toma el número que ingrese el usuario de la cantidad de productos escogidos deseada. 
    String pedido; //String de concatenación de todos los productos y sus cantidades que escoja el usuario.
    String mensajes;
    String almacen;


    /**
     * Creates new form InterfazPrincipal
     */
    
    public static InterfazMenuInicial menuInicial; 
            
    public InterfazPrincipal(InterfazMenuInicial menuInicial) {
        initComponents();
        //Aquí se rellena todo
        this.menuInicial = menuInicial;
        cbAlmacen.addItem("A");
        cbAlmacen.addItem("B");
        cbProducto.addItem("Pantalla");
        cbProducto.addItem("Audífonos");


        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cbAlmacen = new javax.swing.JComboBox<>();
        lblAlmacen = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        cbProducto = new javax.swing.JComboBox<>();
        buttonAgregar = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        buttonFuncionamiento = new javax.swing.JButton();
        lblCantidad1 = new javax.swing.JLabel();
        buttonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(cbAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        lblAlmacen.setText("Almacén");
        jPanel3.add(lblAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lblProducto.setText("Producto");
        jPanel3.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jPanel3.add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, -1));

        buttonAgregar.setText("Agregar");
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
        });
        jPanel3.add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        lblCantidad.setText("Su pedido");
        jPanel3.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 60, -1));

        buttonFuncionamiento.setText("Funcionamiento");
        jPanel3.add(buttonFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        lblCantidad1.setText("Cantidad");
        jPanel3.add(lblCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        buttonRegresar.setText("Regresar");
        buttonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegresarMouseClicked(evt);
            }
        });
        jPanel3.add(buttonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        txtPedido.setColumns(20);
        txtPedido.setRows(5);
        jScrollPane1.setViewportView(txtPedido);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/amazon (2).jpg"))); // NOI18N
        jLabel1.setText("fondo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        menuInicial.setLocationRelativeTo(null);
        menuInicial.setVisible(true);
    }//GEN-LAST:event_buttonRegresarMouseClicked

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        // TODO add your handling code here:
        //cbAlmacen.setEditable(false);
        cbAlmacen.disable();
        System.out.println("\n\n\n\n\n\n\n\n\nCATATO");
        menuInicial.miGrafo.mostrarMatriz();
        System.out.println("\n\n\n\n\n\n\n\n\nCATATO");
        almacen = "Almacen seleccionado: "+cbAlmacen.getSelectedItem()+"\n\n";
        if (pedido == null) {
            producto = cbProducto.getSelectedItem().toString();
            cantidad = txtCantidad.getText().toString();
            pedido = almacen+producto+": "+cantidad+"\n";
            txtPedido.setText(pedido);
            cbProducto.removeItem(producto); //Se elimina de la caja desplegable el producto que acaba de ser seleccionado.            
        } else {
            producto = cbProducto.getSelectedItem().toString();
            cantidad = txtCantidad.getText().toString();
            pedido = pedido+producto+": "+cantidad+"\n";
            txtPedido.setText(pedido);
            cbProducto.removeItem(producto); //Se elimina de la caja desplegable el producto que acaba de ser seleccionado.            
            
        }
    }//GEN-LAST:event_buttonAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal(menuInicial).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonFuncionamiento;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JComboBox<String> cbAlmacen;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables
}
