/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organizedchaos;
import javax.swing.JOptionPane;

/**
 *
 * @author CATATO
 */
public class InterfazAgregarAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAgregarAlmacen
     */
    public static InterfazMenuInicial menuInicial;
    
    public InterfazAgregarAlmacen(InterfazMenuInicial menuInicial) {
        initComponents();
        
        for (int i = 0; i < menuInicial.miGrafo.warehouseList.getSize(); i++) {
            cbAlmacen.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
            cbAlmacenSalida.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
            
            
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAgregar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbAlmacen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        buttonAgregar = new javax.swing.JButton();
        txtDistanciaEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonRegresar = new javax.swing.JButton();
        buttonFuncionamiento = new javax.swing.JButton();
        txtDistanciaSalida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbAlmacenSalida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        jLabel1.setText("Nombre del almacén a agregar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        cbAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(cbAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 110, -1));

        jLabel2.setText("Almacén de entrada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        buttonAgregar.setText("Agregar");
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseEntered(evt);
            }
        });
        jPanel1.add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 120, -1));
        jPanel1.add(txtDistanciaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 120, -1));

        jLabel3.setText("Almacén de salida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel4.setText("Distancia salida");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        buttonRegresar.setText("Regresar");
        jPanel1.add(buttonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        buttonFuncionamiento.setText("Funcionamiento");
        jPanel1.add(buttonFuncionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));
        jPanel1.add(txtDistanciaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 120, -1));

        jLabel5.setText("Distancia entrada");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, -1));

        jPanel1.add(cbAlmacenSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        // TODO add your handling code here:
        boolean continuar = true;
        try{
            String almacenAgregado = txtAgregar.getText();
            int calleEntrada = Integer.parseInt(txtDistanciaEntrada.getText());
            int calleSalida = Integer.parseInt(txtDistanciaSalida.getText());
            String almacenEntrada = cbAlmacen.getSelectedItem().toString();
            String almacenSalida = cbAlmacenSalida.getSelectedItem().toString();
            String conexion = cbAlmacenSalida.getSelectedItem().toString();
            String producto;
            int cantidad;

            //Condición para calle de entrada
            if (menuInicial.miGrafo.warehouseList.getWarehouse(almacenAgregado) == null && almacenEntrada != almacenSalida) {

                Street nuevaCalleEntrada = new Street(almacenAgregado, almacenEntrada, calleEntrada);
                Street nuevaCalleSalida = new Street(almacenSalida, almacenAgregado, calleSalida);
                menuInicial.miGrafo.roadsList.addLast(nuevaCalleEntrada);
                menuInicial.miGrafo.roadsList.addLast(nuevaCalleSalida);
                menuInicial.miGrafo.agregarCalle(nuevaCalleEntrada);       
                menuInicial.miGrafo.agregarCalle(nuevaCalleSalida);
                ListI nuevaListaInventario = new ListI();
                
                int productosAgregar;
                productosAgregar = Integer.parseInt(JOptionPane.showInputDialog("Por favor ingrese la cantidad de productos que desea agregar"));
                for (int i = 0; i < productosAgregar; i++) {
                    producto = JOptionPane.showInputDialog("Por favor ingrese el producto número "+(i+1)+ " que desea agregar");
                    cantidad = Integer.parseInt(JOptionPane.showInputDialog("Por favor la cantidad de " +producto+" disponible en su almacen."));
                    Inventory nuevoInventario = new Inventory(producto, cantidad);
                    nuevaListaInventario.addLast(nuevoInventario);   
                }
                Warehouse nuevoAlmacen = new Warehouse(almacenAgregado, nuevaListaInventario);
                //menuInicial.miGrafo.warehouseList.addLast(nuevoAlmacen);
                //menuInicial.miGrafo.warehouseList.showNodes();
                menuInicial.miGrafo = menuInicial.miGrafo.agregarAlmacen(nuevoAlmacen, nuevaCalleSalida, nuevaCalleSalida);
                
                JOptionPane.showMessageDialog(null, "Almacén agregado exitosamente");
                menuInicial.miGrafo.mostrarMatriz();
                menuInicial.miGrafo.roadsList.showNodes();
                
                
            }           
          
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error. Dato inválido. Para máyor información revise el funcionamiento.");
        }
        
        int agregarOtro = JOptionPane.showConfirmDialog(null, "¿Desea agregar otro almacén?");
        if (agregarOtro == 0) {
            txtAgregar.setText("");
            txtDistanciaEntrada.setText("");
            txtDistanciaSalida.setText("");
            cbAlmacen.removeAllItems();
            cbAlmacenSalida.removeAllItems();
            for (int i = 0; i < menuInicial.miGrafo.warehouseList.getSize(); i++) {
                cbAlmacen.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
                cbAlmacenSalida.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
            }
        } 
        else {
            txtAgregar.setText("");
            txtDistanciaEntrada.setText("");
            txtDistanciaSalida.setText("");
            cbAlmacen.removeAllItems();
            cbAlmacenSalida.removeAllItems();
            for (int i = 0; i < menuInicial.miGrafo.warehouseList.getSize(); i++) {
                cbAlmacen.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
                cbAlmacenSalida.addItem(menuInicial.miGrafo.warehouseList.getWarehouse(i).name);
            this.setVisible(false); //Tiene que hacerse dispose para que la próxima vez que se llame empiece desde cero
            }
        }
    }//GEN-LAST:event_buttonAgregarMouseClicked

    private void buttonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgregarMouseEntered

    private void cbAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgregarAlmacen(menuInicial).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonFuncionamiento;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JComboBox<String> cbAlmacen;
    private javax.swing.JComboBox<String> cbAlmacenSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtDistanciaEntrada;
    private javax.swing.JTextField txtDistanciaSalida;
    // End of variables declaration//GEN-END:variables
}
